# Generated by Django 3.2.4 on 2021-06-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('prescription', models.TextField(max_length=500, null=True)),
                ('datetime', models.CharField(max_length=100, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('is_booked', models.BooleanField(default=False, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.patient')),
            ],
        ),
    ]
